"""Safe ownership records for indexes generated in an alignment output directory."""

from __future__ import annotations

import json
import logging
import os
import secrets
import stat
import tempfile
from collections.abc import Iterable
from contextlib import suppress
from pathlib import Path
from typing import NoReturn

from vntyper.scripts.alignment_contract import index_candidate_names

logger = logging.getLogger(__name__)

_PROVENANCE_VERSION = 1
_PROVENANCE_SUFFIX = ".vntyper.json"


def _reject(message: str) -> NoReturn:
    logger.error(message)
    raise ValueError(message)


def _provenance_path(index_path: str | Path) -> Path:
    return Path(f"{index_path}{_PROVENANCE_SUFFIX}")


def _same_file(left: str | Path, right: str | Path) -> bool:
    try:
        return os.path.samefile(left, right)
    except OSError:
        return False


def _atomic_symlink(target: str | Path, link_path: str | Path) -> None:
    target_absolute = os.path.abspath(target)
    destination = Path(link_path)
    if destination.is_symlink() and os.readlink(destination) == target_absolute:
        return
    for _ in range(100):
        temporary = destination.parent / f".{destination.name}.{secrets.token_hex(8)}.tmp"
        try:
            os.symlink(target_absolute, temporary)
        except FileExistsError:
            continue
        try:
            os.replace(temporary, destination)
        except OSError:
            with suppress(OSError):
                os.unlink(temporary)
            raise
        return
    message = f"Unable to allocate a temporary symlink beside {destination}"
    logger.error(message)
    raise RuntimeError(message)


def _protected_collision(path: Path, protected_paths: Iterable[str | Path]) -> str | None:
    absolute = os.path.abspath(path)
    for protected in protected_paths:
        protected_absolute = os.path.abspath(protected)
        if absolute == protected_absolute:
            return protected_absolute
        if os.path.lexists(path) and _same_file(path, protected):
            return protected_absolute
    return None


def _validate_provenance_entry(path: Path, protected_paths: Iterable[str | Path]) -> None:
    collision = _protected_collision(path, protected_paths)
    if collision is not None:
        _reject(f"Generated-index provenance {path} aliases protected source {collision}")
    if path.is_symlink():
        _reject(f"Generated-index provenance must not be a symlink: {path}")
    try:
        mode = path.lstat().st_mode
    except OSError as error:
        _reject(f"Unable to inspect generated-index provenance {path}: {error}")
    if not stat.S_ISREG(mode):
        _reject(f"Generated-index provenance has a wrong type: {path}")


def _fingerprint(index_path: Path) -> dict[str, int | str]:
    if index_path.is_symlink():
        _reject(f"Generated index must not be a symlink: {index_path}")
    try:
        index_stat = index_path.lstat()
    except OSError as error:
        _reject(f"Unable to inspect generated index {index_path}: {error}")
    if not stat.S_ISREG(index_stat.st_mode):
        _reject(f"Generated index has a wrong type: {index_path}")
    return {
        "version": _PROVENANCE_VERSION,
        "index_name": index_path.name,
        "device": index_stat.st_dev,
        "inode": index_stat.st_ino,
        "size": index_stat.st_size,
        "mtime_ns": index_stat.st_mtime_ns,
    }


def _read_provenance(path: Path) -> object:
    descriptor: int | None = None
    try:
        descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
        with os.fdopen(descriptor, encoding="utf-8") as handle:
            descriptor = None
            return json.load(handle)
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        _reject(f"Unable to read generated-index provenance {path}: {error}")
    finally:
        if descriptor is not None:
            with suppress(OSError):
                os.close(descriptor)


def generated_index_is_owned(
    index_path: str | Path,
    protected_paths: Iterable[str | Path],
) -> bool:
    """Validate whether a reserved index entry was generated by VNtyper.

    Args:
        index_path: Reserved run-local index path to inspect.
        protected_paths: Patient alignment and selected source index paths.

    Returns:
        ``True`` only for a regular index with matching provenance. Missing
        entries and source-index symlinks without provenance return ``False``.

    Raises:
        ValueError: If provenance is missing, unsafe, malformed, or stale for a
            regular index, or exists without a regular generated index.
    """
    protected = tuple(protected_paths)
    index = Path(index_path)
    provenance = _provenance_path(index)
    index_exists = os.path.lexists(index)
    provenance_exists = os.path.lexists(provenance)
    if not index_exists or index.is_symlink():
        if provenance_exists:
            _reject(f"Generated-index provenance exists without its owned regular index: {provenance}")
        return False
    if not index.is_file():
        if provenance_exists:
            _reject(f"Generated-index provenance exists for a wrong-type index: {provenance}")
        return False
    collision = _protected_collision(index, protected)
    if collision is not None:
        _reject(f"Generated index {index} resolves to the same file as protected source {collision}")
    if not provenance_exists:
        _reject(f"Regular reserved index has no generated-index provenance: {index}")
    _validate_provenance_entry(provenance, protected)
    payload = _read_provenance(provenance)
    if payload != _fingerprint(index):
        _reject(f"Generated-index provenance is stale or malformed for {index}")
    return True


def write_generated_index_provenance(
    index_path: str | Path,
    protected_paths: Iterable[str | Path],
    *,
    replace_owned: bool,
) -> None:
    """Atomically record ownership of a newly installed regular index.

    Args:
        index_path: Newly generated run-local index path.
        protected_paths: Patient alignment and selected source index paths.
        replace_owned: Whether a previously validated ownership record may be
            atomically replaced after rebuilding its index.

    Raises:
        ValueError: If the index or record is unsafe, or the record cannot be
            written and installed without following a link.
    """
    protected = tuple(protected_paths)
    index = Path(index_path)
    collision = _protected_collision(index, protected)
    if collision is not None:
        _reject(f"Generated index {index} resolves to the same file as protected source {collision}")
    payload = _fingerprint(index)
    provenance = _provenance_path(index)
    if os.path.lexists(provenance):
        if not replace_owned:
            _reject(f"Generated-index provenance collision will not be replaced: {provenance}")
        _validate_provenance_entry(provenance, protected)
    elif replace_owned:
        _reject(f"Previously owned generated-index provenance disappeared: {provenance}")

    temporary_path: Path | None = None
    exclusive_install_succeeded = False
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=provenance.parent,
            prefix=f".{provenance.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            json.dump(payload, temporary, sort_keys=True)
            temporary.write("\n")
        if replace_owned:
            os.replace(temporary_path, provenance)
        else:
            os.link(temporary_path, provenance)
            exclusive_install_succeeded = True
            os.unlink(temporary_path)
        temporary_path = None
    except OSError as error:
        if exclusive_install_succeeded:
            try:
                os.unlink(provenance)
            except OSError as rollback_error:
                message = (
                    f"Unable to write generated-index provenance {provenance}: {error}; "
                    f"unable to roll back installed provenance: {rollback_error}"
                )
                logger.error(message)
                raise RuntimeError(message) from rollback_error
        _reject(f"Unable to write generated-index provenance {provenance}: {error}")
    finally:
        if temporary_path is not None:
            with suppress(OSError):
                os.unlink(temporary_path)


def remove_generated_index_provenance(
    index_path: str | Path,
    protected_paths: Iterable[str | Path],
) -> None:
    """Remove a previously validated generated-index ownership record.

    Args:
        index_path: Run-local index whose ownership record is obsolete.
        protected_paths: Patient alignment and selected source index paths.

    Raises:
        ValueError: If the record is missing, unsafe, or cannot be removed.
    """
    protected = tuple(protected_paths)
    provenance = _provenance_path(index_path)
    if not os.path.lexists(provenance):
        _reject(f"Generated-index provenance disappeared before removal: {provenance}")
    _validate_provenance_entry(provenance, protected)
    try:
        os.unlink(provenance)
    except OSError as error:
        _reject(f"Unable to remove generated-index provenance {provenance}: {error}")


def _reserve_index_tombstone(index_path: Path) -> Path:
    with tempfile.NamedTemporaryFile(
        dir=index_path.parent,
        prefix=f".{index_path.name}.",
        suffix=".tombstone",
        delete=False,
    ) as temporary:
        return Path(temporary.name)


def _stage_owned_index(index_path: Path) -> Path:
    tombstone = _reserve_index_tombstone(index_path)
    try:
        os.replace(index_path, tombstone)
    except OSError as error:
        with suppress(OSError):
            os.unlink(tombstone)
        _reject(f"Unable to stage generated index {index_path} for an atomic transition: {error}")
    return tombstone


def _restore_owned_index(tombstone: Path, index_path: Path, operation_error: Exception) -> None:
    try:
        os.replace(tombstone, index_path)
    except OSError as rollback_error:
        message = (
            f"Generated-index transition failed for {index_path}: {operation_error}; "
            f"unable to restore the old owned index: {rollback_error}"
        )
        logger.error(message)
        raise RuntimeError(message) from rollback_error


def _discard_committed_tombstone(tombstone: Path, index_path: Path) -> None:
    try:
        os.unlink(tombstone)
    except OSError as error:
        logger.warning(
            f"Generated-index transition committed for {index_path}, but its rollback tombstone "
            f"could not be removed: {tombstone}: {error}"
        )


def _install_generated_index(
    temporary_index: str | Path,
    index_path: str | Path,
    protected_paths: Iterable[str | Path],
    *,
    replace_owned: bool,
) -> None:
    protected = tuple(protected_paths)
    temporary = Path(temporary_index)
    index = Path(index_path)
    if not replace_owned:
        os.replace(temporary, index)
        try:
            write_generated_index_provenance(index, protected, replace_owned=False)
        except Exception:
            if not os.path.lexists(_provenance_path(index)):
                try:
                    os.unlink(index)
                except OSError as cleanup_error:
                    message = (
                        f"Unable to remove unowned generated index after provenance failure: {index}: {cleanup_error}"
                    )
                    logger.error(message)
                    raise RuntimeError(message) from cleanup_error
            raise
        return

    tombstone = _stage_owned_index(index)
    try:
        os.replace(temporary, index)
        write_generated_index_provenance(index, protected, replace_owned=True)
    except Exception as error:
        _restore_owned_index(tombstone, index, error)
        raise
    _discard_committed_tombstone(tombstone, index)


def _replace_owned_index_with_symlink(
    index_path: str | Path,
    source_index: str | Path,
    protected_paths: Iterable[str | Path],
) -> None:
    protected = tuple(protected_paths)
    index = Path(index_path)
    tombstone = _stage_owned_index(index)
    try:
        _atomic_symlink(source_index, index)
        remove_generated_index_provenance(index, protected)
    except Exception as error:
        _restore_owned_index(tombstone, index, error)
        raise
    _discard_committed_tombstone(tombstone, index)


def _remove_owned_index_pair(index_path: str | Path, protected_paths: Iterable[str | Path]) -> None:
    protected = tuple(protected_paths)
    index = Path(index_path)
    tombstone = _stage_owned_index(index)
    try:
        remove_generated_index_provenance(index, protected)
    except Exception as error:
        _restore_owned_index(tombstone, index, error)
        raise
    try:
        os.unlink(tombstone)
    except OSError as error:
        _reject(f"Unable to remove stale generated index {index}: {error}")


def _remove_stale_view_indexes(
    view_path: str,
    file_format: str,
    keep: str | None,
    owned_indexes: set[Path],
    protected_paths: Iterable[str | Path],
) -> None:
    protected = tuple(protected_paths)
    for candidate in index_candidate_names(view_path, file_format):
        if candidate != keep and os.path.lexists(candidate):
            if Path(candidate) in owned_indexes:
                _remove_owned_index_pair(candidate, protected)
            else:
                try:
                    os.unlink(candidate)
                except OSError as error:
                    _reject(f"Unable to remove stale view index {candidate}: {error}")
