"""
generate_report.py

Module Purpose:
---------------
Renders the per-sample HTML report from ``pipeline_summary.json``.

What is left here is the I/O half: reading the summary and the fastp and log
files, shelling out to ``create_report`` for the IGV panel, assembling the
template context and writing the HTML. Everything that turns a value into a
displayed string lives in :mod:`vntyper.scripts.report_formatting`, and the
screening interpretation lives in :mod:`vntyper.scripts.screening_summary` --
both extracted under AGENTS.md rule 3, which is what made either of them
testable.

Two things about this module are load-bearing and easy to break:

* The five pipeline-summary step names are matched by exact string comparison.
  A typo does not fail; it silently drops a report section (AGENTS.md trap 5),
  so they come from :mod:`vntyper.scripts.summary_steps` and are never spelled
  out here.
* The coverage field names come from
  :data:`vntyper.scripts.coverage_stats.COVERAGE_COLUMNS` (contract C1) by way
  of ``report_formatting``. They are read with ``.get(name, 0)``, so a rename
  makes the report state that an uncovered sample has full coverage.
"""

import json
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape

from vntyper.scripts.coverage_qc import evaluate_coverage_qc
from vntyper.scripts.output_paths import contained_output_path
from vntyper.scripts.report_formatting import (
    ADVNTR_CELL_FORMATS,
    ADVNTR_DISPLAY_COLUMNS,
    EMPTY_SESSION_DICTIONARY,
    EMPTY_TABLE_JSON,
    KESTREL_DISPLAY_CELL_FORMATS,
    KESTREL_DISPLAY_COLUMNS,
    MISSING_AS_OK,
    confidence_html,
    drop_empty_result_rows,
    escaped_table_html,
    extract_igv_fragments,
    flag_html,
    flagged_row_count,
    format_number_columns,
    js_json_literal,
    parse_coverage_stats,
    row_count_statement,
    select_display_columns,
    summarise_fastp,
    threshold_icon,
)
from vntyper.scripts.report_identity import (
    ASSAY_NAME,
    REPORT_TITLE_PREFIX,
    RESEARCH_USE_STATEMENT,
    format_input_files,
    format_region,
    format_run_timestamp,
    input_file_names,
    recorded_or_not,
    resolve_sample_name,
)
from vntyper.scripts.screening_summary import build_screening_summary, load_report_config

# These five names are matched by exact string comparison against what pipeline.py
# records. A typo does not fail - it silently drops a report section (AGENTS.md
# trap 5), so they are named, never spelled out.
from vntyper.scripts.summary_steps import (
    STEP_ABSENT,
    STEP_ADVNTR,
    STEP_BAM_HEADER,
    STEP_COVERAGE,
    STEP_CROSS_MATCH,
    STEP_KESTREL,
    STEP_UNREADABLE,
    get_step,
    get_step_data,
    get_step_result,
    get_step_state,
)

logger = logging.getLogger(__name__)

#: Shown when a coverage figure could not be computed.
NOT_CALCULATED = "Not calculated"

#: How each results table names itself in its visible/total row-count statement.
KESTREL_ROW_NOUN = "Kestrel"
ADVNTR_ROW_NOUN = "adVNTR"


def load_pipeline_summary(summary_file_path):
    """
    Loads the pipeline summary JSON file generated by the pipeline.

    Args:
        summary_file_path (str or Path): Path to the pipeline summary file.

    Returns:
        dict: The loaded summary dictionary or an empty dict if load fails.
    """
    logger.info("Loading pipeline summary from %s", summary_file_path)
    if not os.path.exists(summary_file_path):
        logger.error("Pipeline summary file not found: %s", summary_file_path)
        return {}
    try:
        with open(summary_file_path) as f:
            summary = json.load(f)
        logger.debug("Pipeline summary loaded successfully.")
        return summary
    except Exception as e:
        logger.error("Failed to load pipeline summary: %s", e)
        return {}


def run_igv_report(bed_file, bam_file, fasta_file, output_html, flanking=50, vcf_file=None, config=None):
    """
    Wrapper around `create_report` IGV command. If config is provided and flanking
    is not explicitly set, we fall back to config's default_values.flanking.
    Skips passing None for track arguments (vcf_file or bam_file).
    """
    logger.debug("run_igv_report called with:")
    logger.debug("  bed_file=%s", bed_file)
    logger.debug("  bam_file=%s", bam_file)
    logger.debug("  fasta_file=%s", fasta_file)
    logger.debug("  output_html=%s", output_html)
    logger.debug("  vcf_file=%s", vcf_file)
    logger.debug("  flanking=%s", flanking)

    if config is not None and flanking == 50:
        flanking = config.get("default_values", {}).get("flanking", 50)
        logger.debug("Flanking region set to %s based on config.", flanking)

    bed_file = str(bed_file) if bed_file else None
    bam_file = str(bam_file) if bam_file else None
    fasta_file = str(fasta_file) if fasta_file else None
    output_html = str(output_html) if output_html else None

    igv_report_cmd = [
        "create_report",
        bed_file,
        "--flanking",
        str(flanking),
        "--fasta",
        fasta_file,
        "--tracks",
    ]

    # Build tracks list with defensive programming (verify files exist)
    # Follows SOLID principles: defensive checks + clear logging
    tracks = []

    if vcf_file:
        # Verify file exists before adding to tracks (defensive programming)
        if os.path.exists(vcf_file):
            tracks.append(str(vcf_file))
            logger.debug(f"Adding VCF track: {vcf_file}")
        else:
            logger.warning(f"VCF file specified but not found: {vcf_file}. Skipping VCF track.")
    else:
        logger.info("No VCF file provided. IGV report will not include VCF track.")

    if bam_file:
        if os.path.exists(bam_file):
            tracks.append(str(bam_file))
            logger.debug(f"Adding BAM track: {bam_file}")
        else:
            logger.warning(f"BAM file specified but not found: {bam_file}. Skipping BAM track.")

    if not tracks:
        logger.error("No valid tracks (VCF or BAM) available for IGV report. Report may be empty or fail.")

    igv_report_cmd.extend(tracks)
    igv_report_cmd.extend(["--output", output_html])

    logger.debug("IGV report command: %s", " ".join([str(x) for x in igv_report_cmd if x]))
    try:
        logger.info("Running IGV report: %s", " ".join([str(x) for x in igv_report_cmd if x]))
        subprocess.run(igv_report_cmd, check=True)
        logger.info("IGV report successfully generated at %s", output_html)
    except subprocess.CalledProcessError as e:
        logger.error("Error generating IGV report: %s", e)
        raise
    except Exception as e:
        logger.error("Unexpected error generating IGV report: %s", e)
        raise


def extract_igv_content(igv_report_html):
    """
    Reads the generated IGV HTML report and extracts the IGV content,
    the tableJson variable, and the sessionDictionary variable from the script.
    Returns empty strings if not found or on error.

    Args:
        igv_report_html (str or Path): Path to the page ``create_report`` wrote.

    Returns:
        tuple[str, str, str]: The container markup, ``tableJson`` and
        ``sessionDictionary``. All three are empty on any read failure.
    """
    logger.debug("extract_igv_content called with igv_report_html=%s", igv_report_html)
    try:
        with open(igv_report_html) as f:
            content = f.read()
    except FileNotFoundError:
        logger.error("IGV report file not found: %s", igv_report_html)
        return "", "", ""
    except Exception as e:
        logger.error("Unexpected error reading IGV report: %s", e)
        return "", "", ""
    return extract_igv_fragments(content)


def load_fastp_output(fastp_file):
    """
    Loads fastp JSON output (e.g., output.json) for summary metrics if available.
    Returns an empty dict if file not found or if parsing fails.
    """
    logger.debug("load_fastp_output called with fastp_file=%s", fastp_file)
    if not os.path.exists(fastp_file):
        logger.warning("fastp output file not found: %s", fastp_file)
        return {}
    try:
        with open(fastp_file) as f:
            data = json.load(f)
        logger.debug("fastp output successfully loaded.")
        return data
    except Exception as e:
        logger.error("Failed to load or parse fastp output: %s", e)
        return {}


def load_pipeline_log(log_file):
    """
    Loads the pipeline log content from the specified log_file.
    Returns a placeholder string if not found or on error.
    """
    logger.info("Loading pipeline log from %s", log_file)
    if not log_file:
        logger.warning("No pipeline log file provided; skipping log loading.")
        return "No pipeline log file was provided."
    if not os.path.exists(log_file):
        logger.warning("Pipeline log file not found: %s", log_file)
        return "Pipeline log file not found."
    try:
        with open(log_file) as f:
            content = f.read()
        logger.debug("Pipeline log successfully loaded.")
        return content
    except Exception as e:
        logger.error("Failed to read pipeline log file: %s", e)
        return "Failed to load pipeline log."


def build_kestrel_frames(kestrel_data):
    """Build the display and matching Kestrel frames from summary rows.

    Two frames come out of one input because they are used for different things:
    the screening summary matches on plain values, while the table shows
    colour-coded HTML. Colour-coding the frame the summary reads would make every
    ``Confidence`` comparison fail against a ``<span>``.

    A run that genotyped and called nothing is *not* a run with a result. Kestrel
    records one there anyway - ``output_empty_result`` writes a row of the literal
    string ``"None"`` with ``Confidence`` set to ``Negative``, so that
    ``kestrel_result.tsv`` has a body - and both frames used to carry it: the table
    rendered ``None None None None None None None None NaN Negative`` and the count
    line called it one Kestrel row (#242). It is dropped here, before either frame
    exists, so the display, the count and the screening match all see the same rows.

    Dropping it cannot move the screening verdict. ``compute_algorithm_result`` reads
    only the first row and every configured Kestrel rule breaks on that row's
    ``Confidence``, so the block's ``default`` - "negative" - is what it returned with
    the placeholder present, and an empty frame returns the same default by the
    shortest path.

    Args:
        kestrel_data (list[dict]): The ``Kestrel Genotyping`` step's rows.

    Returns:
        tuple[pandas.DataFrame, pandas.DataFrame]: The frame to render, and the
        unformatted frame to match on. Both are empty when there are no rows, and when
        the only row is the empty-result placeholder.
    """
    kestrel_data = drop_empty_result_rows(kestrel_data) if kestrel_data else kestrel_data
    if not kestrel_data:
        logger.warning("No Kestrel data found in pipeline summary.")
        return pd.DataFrame(), pd.DataFrame()

    frame = select_display_columns(pd.DataFrame(kestrel_data), KESTREL_DISPLAY_COLUMNS)

    if "Depth Score" in frame.columns:
        try:
            frame["Depth Score"] = pd.to_numeric(frame["Depth Score"], errors="coerce")
        except Exception as e:
            logger.warning("Could not convert 'Depth Score' to numeric: %s", e)
        frame = frame.sort_values(by="Depth Score", ascending=False)

    matching_frame = frame.copy()

    # Every displayed number is produced here, by the formatter its column declares.
    # The browser used to do it, table-agnostically and only when three CDNs
    # resolved, so the same file read differently online and offline (#242). The
    # matching frame is copied first and keeps the unformatted values, because the
    # screening rules compare against them.
    frame = format_number_columns(frame, KESTREL_DISPLAY_CELL_FORMATS)

    if "Confidence" in frame.columns:
        frame["Confidence"] = frame["Confidence"].apply(confidence_html)
    if "Flag" in frame.columns:
        frame["Flag"] = frame["Flag"].apply(flag_html)

    # The remaining cells are escaped by `escaped_table_html`, which renders the frame -
    # once, naming `Confidence` and `Flag` as the columns whose markup we built and which
    # escaped their own values. Escaping here as well would double-escape every other
    # cell, so a motif sequence containing a `<` would reach the reader as `&lt;`.
    logger.debug("Kestrel data extracted from summary and formatted.")
    return frame, matching_frame


def build_advntr_frame(advntr_data):
    """Project the adVNTR rows onto the columns the report shows.

    Args:
        advntr_data (list[dict]): The ``adVNTR Genotyping`` step's rows.

    Returns:
        pandas.DataFrame: The frame to render, empty when there are no rows.
    """
    if not advntr_data:
        return pd.DataFrame()
    frame = pd.DataFrame(advntr_data)
    logger.debug("adVNTR data extracted from summary and formatted.")
    return frame[[col for col in ADVNTR_DISPLAY_COLUMNS if col in frame.columns]]


def build_cross_match_summary(pipeline_summary):
    """Summarise the cross-match step as a sentence *and* the state that sentence describes.

    The boolean is returned alongside the text rather than derived from it. The template
    used to decide emphasis by asking whether the message contained ``"match"``, and both
    fixed sentences do - so "No matches were found" rendered in the positive style. This
    is the same rule that governs ``summary_is_positive`` (AGENTS.md trap 11): emphasis
    comes from the computed state, never from searching the wording.

    Args:
        pipeline_summary (dict): The parsed ``pipeline_summary.json``.

    Returns:
        tuple[str, bool]: The sentence and whether it reports a match. ``("", False)``
            when the cross-match step did not run - no section is rendered, and the flag
            must not default to the emphasised state.
    """
    if get_step(pipeline_summary, STEP_CROSS_MATCH) is None:
        return "", False
    data = get_step_data(pipeline_summary, STEP_CROSS_MATCH)
    is_positive = any(item.get("Match") == "Yes" for item in data)
    if is_positive:
        return "At least one match was found between Kestrel and adVNTR results.", True
    return "No matches were found between Kestrel and adVNTR results.", False


#: The release in which coverage statistics became region-wide (#171). A summary written
#: by an older version carries a ``mean`` over *covered* positions, which is not comparable
#: with the thresholds applied to it today.
REGION_WIDE_MEAN_SINCE = (2, 0, 8)


def _predates_region_wide_mean(version: str | None) -> bool:
    """Whether a recorded pipeline version is older than the region-wide coverage change.

    Args:
        version (str | None): The ``version`` recorded in ``pipeline_summary.json``.

    Returns:
        bool: True only when the version parses and is strictly older than
        :data:`REGION_WIDE_MEAN_SINCE`. An absent, empty or unparseable version returns
        False, so an unrecognised summary is left exactly as it is rather than having its
        numbers silently rescaled.
    """
    if not version:
        return False
    parts = version.strip().lstrip("v").split(".")[:3]
    try:
        parsed = tuple(int(part) for part in parts)
    except ValueError:
        logger.debug("Unparseable pipeline version %r; leaving coverage figures untouched.", version)
        return False
    return parsed < REGION_WIDE_MEAN_SINCE


def generate_summary_report(
    output_dir,
    template_dir,
    report_file,
    log_file,
    bed_file=None,
    bam_file=None,
    fasta_file=None,
    flanking=50,
    vcf_file=None,
    config=None,
    sample_name=None,
):
    """
    Generates a summary report based on a pipeline summary JSON file.
    Instead of parsing results from subfolders, the report now loads the output summary file (JSON)
    and renders the report based on that content. The main configuration is passed in via 'config'.
    This module additionally loads its own report-specific configuration from report_config.json.
    The header information extracted from the BAM Header Parsing step (including warning,
    alignment_pipeline, assembly_text, and assembly_contig) is included in the report context.

    Args:
        output_dir (str): Output directory for the report.
        template_dir (str): Directory containing the report template.
        report_file (str): Name of the report file.
        log_file (str): Path to the pipeline log file.
        bed_file (str, optional): Path to the BED file for IGV reports.
        bam_file (str, optional): Path to the BAM file for IGV reports.
        fasta_file (str, optional): Path to the reference FASTA file for IGV reports.
        flanking (int, optional): Size of the flanking region for IGV reports.
        vcf_file (str, optional): Path to the sorted/indexed VCF file.
        config (dict): Main configuration dictionary (passed from the pipeline).
        sample_name (str, optional): What the report calls its sample, in the
            title, the heading and the header block. Reachable through
            ``vntyper report --sample-name``; the pipeline passes nothing and the
            name is derived from the summary's own ``input_files`` instead - see
            :func:`~vntyper.scripts.report_identity.resolve_sample_name`.

    Raises:
        ValueError: If config is not provided.
    """
    logger.debug("---- DEBUG: Entered generate_summary_report ----")
    logger.debug(
        "Called with output_dir=%s, template_dir=%s, report_file=%s",
        output_dir,
        template_dir,
        report_file,
    )
    logger.debug(
        "bed_file=%s, bam_file=%s, fasta_file=%s, flanking=%s, log_file=%s, vcf_file=%s",
        bed_file,
        bam_file,
        fasta_file,
        flanking,
        log_file,
        vcf_file,
    )

    if config is None:
        raise ValueError("Config dictionary must be provided to generate_summary_report")

    # Load the script-specific report configuration.
    report_config = load_report_config()

    # Resolve flanking region from main config if needed.
    if flanking == 50:
        flanking = config.get("default_values", {}).get("flanking", 50)
        logger.debug("Flanking region set to %s based on config.", flanking)

    thresholds = config.get("thresholds", {})
    mean_vntr_cov_threshold = thresholds.get("mean_vntr_coverage", 100)
    percent_vntr_uncovered_threshold = thresholds.get("percent_vntr_uncovered", 50.0)
    dup_rate_cutoff = thresholds.get("duplication_rate", 0.1)
    q20_rate_cutoff = thresholds.get("q20_rate", 0.8)
    q30_rate_cutoff = thresholds.get("q30_rate", 0.7)
    passed_filter_rate_cutoff = thresholds.get("passed_filter_reads_rate", 0.8)

    # Load the pipeline summary JSON.
    summary_file_path = Path(output_dir) / "pipeline_summary.json"
    pipeline_summary = load_pipeline_summary(summary_file_path)

    # Extract input_files and pipeline_version from the summary.
    input_files = pipeline_summary.get("input_files", {})
    pipeline_version = pipeline_summary.get("version", "unknown")

    # Who this report is about (#242). Every report was titled "Summary Report",
    # so two of them were indistinguishable in two browser tabs and a printed one
    # carried no identity at all. Three levels: an explicit `--sample-name` here,
    # then the name the *run* recorded - the same string Kestrel embedded, so the
    # report and the VCF cannot disagree - then a derivation from `input_files`,
    # which is what every summary written before the field existed still uses.
    resolved_sample_name = resolve_sample_name(
        sample_name,
        *input_file_names(input_files),
        recorded=pipeline_summary.get("sample_name"),
    )
    logger.info("Report sample name resolved to %r.", resolved_sample_name)

    # How the run's reference was actually resolved (#163) - the BWA reference for
    # FASTQ, or whatever the alignment plan proved for BAM/CRAM, never a BWA path a
    # BAM/CRAM run never opened (MAJOR 5, milestone-5 PR-2 review; see
    # `pipeline_alignment.resolve_summary_reference_provenance`). A summary written
    # before this was recorded simply omits these, and the template renders nothing for
    # them - see AGENTS.md trap 5 on step names for the same "absent key, no section"
    # pattern.
    reference_assembly_requested = pipeline_summary.get("reference_assembly_requested")
    reference_key_used = pipeline_summary.get("reference_key_used")
    reference_path = pipeline_summary.get("reference_path")
    reference_source_effective = pipeline_summary.get("reference_source_effective")

    # Header info from the BAM Header Parsing step, whose parsed_result is a flat
    # object rather than {"data": [...]}.
    header_info = get_step_result(pipeline_summary, STEP_BAM_HEADER)
    header_warning = header_info.get("warning", "")
    alignment_pipeline = header_info.get("alignment_pipeline", "")
    assembly_text = header_info.get("assembly_text", "")
    assembly_contig = header_info.get("assembly_contig", "")

    # VNTR coverage statistics, keyed by the frozen coverage schema (contract C1).
    coverage_rows = get_step_data(pipeline_summary, STEP_COVERAGE)
    coverage = parse_coverage_stats(coverage_rows)
    mean_vntr_coverage = coverage["mean"]
    percent_vntr_uncovered = coverage["percent_uncovered"]

    # A summary written before 2.0.8 carries no `coverage_qc` column, and its `mean` is the
    # mean over *covered* positions rather than over the region (#171) - so judging it with
    # the new rule would be too lenient: an old mean of 150 at 40% uncovered passes a 100x
    # threshold, while the region-wide mean it stands for is 90 and fails.
    #
    # The mean is recoverable exactly rather than approximately. `percent_uncovered` was
    # already correct before 2.0.8, and with S = sum(depths), c = covered, T = region:
    # (S/c) * (1 - (T-c)/T) = (S/c)(c/T) = S/T. The golden-cohort gate confirmed this
    # identity holds on 61 of 61 cases. So correct the number and judge the corrected one.
    # Two signals are required, and the default is to change nothing. A missing
    # `coverage_qc` column alone is not proof of an old summary - a hand-built or
    # third-party one may simply omit it, and silently rescaling its mean would be worse
    # than the problem being fixed. So also require the recorded version to parse to
    # something older than 2.0.8; an absent or unreadable version leaves the number alone.
    legacy_summary = (
        bool(coverage_rows) and "coverage_qc" not in coverage_rows[0] and _predates_region_wide_mean(pipeline_version)
    )
    mean_for_qc = mean_vntr_coverage
    if legacy_summary and mean_vntr_coverage is not None and percent_vntr_uncovered is not None:
        mean_for_qc = round(mean_vntr_coverage * (1 - percent_vntr_uncovered / 100), 2)
        logger.info(
            "Coverage summary predates 2.0.8; correcting its covered-bases mean %.2f to the "
            "region-wide %.2f before applying the QC rule (#171).",
            mean_vntr_coverage,
            mean_for_qc,
        )

    # Recomputed rather than read out of the stored `coverage_qc`, so `vntyper report` still
    # works against a summary written before #172. Given the same thresholds both sides
    # evaluate the *published* two-decimal figures - serialised with `:.2f` - so they agree.
    # Supplying different thresholds to `vntyper report` deliberately yields a different
    # verdict from the one stored at run time; that is the caller asking for one.
    coverage_qc = evaluate_coverage_qc(
        mean_for_qc,
        percent_vntr_uncovered,
        mean_vntr_cov_threshold,
        percent_vntr_uncovered_threshold,
    )

    # Three states, not two. "Recorded" is not "produced a readable result": when
    # `kestrel_result.tsv` is absent, `record_step` flags the step `result_file_missing`
    # and still records it with an empty `data` list (#212) - the same shape a run that
    # genotyped and called nothing produces. Asking only whether the step is present
    # therefore renders a failed stage as a negative, which is a claim the run never
    # established. This is the first consumer of that flag.
    kestrel_state = get_step_state(pipeline_summary, STEP_KESTREL)
    kestrel_df, kestrel_df_raw = build_kestrel_frames(get_step_data(pipeline_summary, STEP_KESTREL))

    advntr_available = get_step(pipeline_summary, STEP_ADVNTR) is not None
    advntr_df = build_advntr_frame(get_step_data(pipeline_summary, STEP_ADVNTR))

    pipeline_log_content = load_pipeline_log(log_file)

    # IGV report generation (if applicable)
    if bed_file and os.path.exists(bed_file):
        logger.info("Running IGV report for BED file: %s", bed_file)
        igv_report_file = Path(output_dir) / "igv_report.html"
        run_igv_report(
            bed_file,
            bam_file,
            fasta_file,
            igv_report_file,
            flanking=flanking,
            vcf_file=vcf_file,
            config=config,
        )
    else:
        logger.warning("BED file does not exist or not provided. Skipping IGV report generation.")
        igv_report_file = None

    if igv_report_file and igv_report_file.exists():
        igv_content, table_json, session_dictionary = extract_igv_content(igv_report_file)
    else:
        logger.warning("IGV report file not found. Skipping IGV content.")
        igv_content, table_json, session_dictionary = "", "", ""

    fastp = summarise_fastp(load_fastp_output(Path(output_dir) / "fastq_bam_processing/output.json"))

    coverage_icon, coverage_color = threshold_icon(
        mean_vntr_coverage, mean_vntr_cov_threshold, higher_better=True, on_missing=MISSING_AS_OK
    )
    uncovered_icon, uncovered_color = threshold_icon(
        percent_vntr_uncovered, percent_vntr_uncovered_threshold, higher_better=False, on_missing=MISSING_AS_OK
    )
    dup_icon, dup_color = threshold_icon(fastp.duplication_rate, dup_rate_cutoff, higher_better=False)
    q20_icon, q20_color = threshold_icon(fastp.q20_rate, q20_rate_cutoff)
    q30_icon, q30_color = threshold_icon(fastp.q30_rate, q30_rate_cutoff)
    pf_icon, pf_color = threshold_icon(fastp.passed_filter_rate, passed_filter_rate_cutoff)

    # "" for an empty frame, which is what the template's authored empty states hang
    # on. This used to call `to_html` directly, bypassing the helper written for
    # exactly this: an empty frame produced a headerless, bodyless `<table>` - a stray
    # empty box under the heading - and every cell was escaped a step earlier instead.
    kestrel_html = escaped_table_html(
        kestrel_df,
        classes="table table-bordered table-striped hover compact order-column table-sm",
        html_columns=("Confidence", "Flag"),
        table_id="kestrel_table",
    )
    kestrel_row_summary = (
        row_count_statement(len(kestrel_df), flagged_row_count(kestrel_df_raw), noun=KESTREL_ROW_NOUN)
        if kestrel_html
        else ""
    )
    logger.debug("Kestrel results converted to HTML.")

    advntr_row_summary = ""
    if not advntr_available:
        # The template's `{% if advntr_available and advntr_highlight %}` cannot reach
        # this branch's markup, so the paragraph that used to be built here was never
        # rendered by any report - the `{% else %}` beneath that guard prints its own,
        # differently worded line. One state, one sentence, and it is the template's.
        advntr_html = ""
        logger.debug("adVNTR was not performed; the template states so.")
    elif advntr_df.empty:
        advntr_html = "<p>No pathogenic variants identified by adVNTR.</p>"
        logger.debug("adVNTR was performed but no variants identified; adding negative message.")
    else:
        # Rendered from a copy: `advntr_df` itself is what the screening rules match
        # on (`VID`, `Flag`), so it has to keep the unformatted values.
        advntr_display = format_number_columns(advntr_df, ADVNTR_CELL_FORMATS)
        if "Flag" in advntr_display.columns:
            advntr_display["Flag"] = advntr_display["Flag"].apply(flag_html)
        advntr_html = escaped_table_html(
            advntr_display,
            classes="table table-bordered table-striped hover compact table-sm",
            html_columns=("Flag",),
        )
        advntr_row_summary = row_count_statement(len(advntr_df), flagged_row_count(advntr_df), noun=ADVNTR_ROW_NOUN)
        logger.debug("adVNTR results converted to HTML.")

    cross_match_message, cross_match_is_positive = build_cross_match_summary(pipeline_summary)

    # Autoescaping is on: everything reaching the report from a sample - file
    # names, BAM header fields, motif sequences, log lines - is attacker-influenced
    # and the report is a file people forward. The fragments we build ourselves are
    # marked `|safe` at their interpolation points in the template, and the two
    # results tables and the Confidence spans are escaped before they get there.
    env = Environment(loader=FileSystemLoader(template_dir), autoescape=select_autoescape(["html"]))
    try:
        template = env.get_template("report_template.html")
        logger.debug("Jinja2 template 'report_template.html' loaded successfully.")
    except Exception as e:
        logger.error("Failed to load Jinja2 template: %s", e)
        raise

    # Match on the sorted, unformatted frame: the displayed one has HTML in its
    # Confidence cells and would match nothing.
    screening = build_screening_summary(
        kestrel_df_raw,
        advntr_df,
        advntr_available,
        coverage_qc,
        report_config,
    )
    logger.debug("Summary text generated: %s", screening.text)

    def shown(value):
        """Render a coverage figure, or say it was not calculated."""
        return value if value is not None else NOT_CALCULATED

    def _rounded(value):
        """Two decimal places, server-side.

        The cohort template runs `applyRounding` over every table it initialises and
        strips trailing zeroes, so a figure left to the browser renders differently
        online and offline (#242). Rounding here makes the printed value a property of
        the run rather than of the reader's network.
        """
        return None if value is None else round(value, 2)

    context = {
        "kestrel_highlight": kestrel_html,
        # The two facts the empty states branch on, both derived from the computed
        # state rather than from the shape of the data - which is what conflated them.
        # `vntyper report` renders a supplied summary (#207) that need not carry the
        # step at all, and a run whose Kestrel stage failed carries one that produced
        # nothing; rendering either as "found nothing" asserts something the run never
        # established. (adVNTR still asks only whether its step is recorded. Its
        # section already words the absent case as a disjunction rather than as a
        # negative, so the same conflation there is not the same defect - but it is the
        # same shape, and it is worth closing separately.)
        "kestrel_step_recorded": kestrel_state != STEP_ABSENT,
        "kestrel_result_unreadable": kestrel_state == STEP_UNREADABLE,
        # The visible/total statement beside each table, counted here from the frame.
        # DataTables' own "Showing 1 to 3 of 3 entries" footer is switched off: it is
        # a second count that contradicts this one whenever a CDN fails (#242). It is
        # empty when there is no table: the sentence exists to say that nothing was
        # withheld from the rows below it, so counting a non-result defeats its purpose.
        "kestrel_row_summary": kestrel_row_summary,
        "advntr_highlight": advntr_html,
        "advntr_row_summary": advntr_row_summary,
        "advntr_available": advntr_available,
        "log_content": pipeline_log_content,
        "igv_content": igv_content,
        # Interpolated straight into a <script> block, so they must parse even
        # when there is no IGV report at all.
        "table_json": js_json_literal(table_json, EMPTY_TABLE_JSON),
        "session_dictionary": js_json_literal(session_dictionary, EMPTY_SESSION_DICTIONARY),
        # Two timestamps, labelled, because they are different facts. `report_date`
        # is `datetime.now()` at render, so re-running `vntyper report` over an
        # archived run restamped the only date on the page and the artefact
        # silently claimed to be newer than the analysis (#242). Both carry a zone:
        # the run time is UTC and this one is the rendering machine's local time,
        # so printing them unqualified beside each other invites the reader to
        # subtract them.
        "report_date": datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M:%S %Z"),
        "run_date": format_run_timestamp(pipeline_summary.get("pipeline_start")),
        # The mapping is rendered by iterating it, not by branching on its shape:
        # the template tested for `fastq1 and fastq2` or `bam`, so the other two
        # shapes `resolve_pipeline_input` emits rendered an empty line.
        "input_files_text": format_input_files(input_files),
        "sample_name": resolved_sample_name,
        "assay_name": ASSAY_NAME,
        "report_title_prefix": REPORT_TITLE_PREFIX,
        # Printed on every archived page. The printed record is the artefact that
        # outlives the HTML, and it is the one that gets filed and forwarded.
        "research_use_statement": RESEARCH_USE_STATEMENT,
        "pipeline_version": pipeline_version,
        # The provenance block. Two of these four rows are *not* new summary keys:
        # `assembly_declared` is the `reference_assembly_requested` `start_summary`
        # has always written, and `assembly_detected` is the BAM-header step's
        # `assembly_text`. Recording either again under a second name would be the
        # divergent-source problem `cli_report.py`'s docstring warns about. Every
        # row says `not recorded by this run` when its source is absent - never
        # `config["default_values"]["reference_assembly"]`, which would mislabel any
        # `--reference-assembly` override and cannot reconstruct `--custom-regions`.
        "summary_schema_version": recorded_or_not(pipeline_summary.get("schema_version")),
        "assembly_declared": recorded_or_not(reference_assembly_requested),
        "assembly_detected": recorded_or_not(assembly_text),
        "region_resolved": format_region(pipeline_summary.get("region_resolved")),
        # `reference_assembly_requested` and `assembly_text` are deliberately absent:
        # they reach the template as `assembly_declared` and `assembly_detected`
        # above. Passing the raw values too would put the same fact in the context
        # twice under two names, which is how the template came to have two places
        # that could disagree about the assembly.
        "reference_key_used": reference_key_used,
        "reference_path": reference_path,
        "reference_source_effective": reference_source_effective,
        "header_warning": header_warning,
        "alignment_pipeline": alignment_pipeline,
        "assembly_contig": assembly_contig,
        "mean_vntr_coverage": shown(coverage["mean"]),
        "median_vntr_coverage": shown(coverage["median"]),
        "stdev_vntr_coverage": shown(coverage["stdev"]),
        "min_vntr_coverage": shown(coverage["min"]),
        "max_vntr_coverage": shown(coverage["max"]),
        "vntr_region_length": shown(coverage["region_length"]),
        "vntr_uncovered_bases": shown(coverage["uncovered_bases"]),
        "percent_vntr_uncovered": shown(coverage["percent_uncovered"]),
        # #222. Two figures with different standing, so they are labelled differently in the
        # template rather than sitting beside the window mean as if interchangeable:
        # the flank depth is comparable between assemblies without qualification, while the
        # array sum is comparable only under the counting policy printed with it.
        "vntr_flank_mean_depth": shown(_rounded(coverage["vntr_flank_mean_depth"])),
        "vntr_flank_bases": shown(coverage["vntr_flank_bases"]),
        "vntr_array_length": shown(coverage["vntr_array_length"]),
        "vntr_array_depth_sum": shown(coverage["vntr_array_depth_sum"]),
        "vntr_array_depth_sum_per_unit_length": shown(_rounded(coverage["vntr_array_depth_sum_per_unit_length"])),
        "depth_sum_reference_length": shown(coverage["depth_sum_reference_length"]),
        "depth_counting_policy": shown(coverage["depth_counting_policy"]),
        "coverage_qc": coverage_qc.status,
        "percent_vntr_uncovered_icon": uncovered_icon,
        "percent_vntr_uncovered_color": uncovered_color,
        "mean_vntr_coverage_icon": coverage_icon,
        "mean_vntr_coverage_color": coverage_color,
        "fastp_available": fastp.available,
        "duplication_rate": fastp.duplication_rate,
        "duplication_rate_icon": dup_icon,
        "duplication_rate_color": dup_color,
        "q20_rate": fastp.q20_rate,
        "q20_icon": q20_icon,
        "q20_color": q20_color,
        "q30_rate": fastp.q30_rate,
        "q30_icon": q30_icon,
        "q30_color": q30_color,
        "passed_filter_rate": fastp.passed_filter_rate,
        "passed_filter_icon": pf_icon,
        "passed_filter_color": pf_color,
        "sequencing_str": fastp.sequencing,
        "summary_text": screening.text,
        "summary_is_positive": screening.is_positive,
        # The full computed screening state, not just `is_positive` - so a report
        # whose state matched no rule (`emphasis == "indeterminate"`) is distinguishable
        # from a genuine negative rather than rendering identically (#242 I2).
        "screening_state": {
            "kestrel_result": screening.kestrel_result,
            "advntr_result": screening.advntr_result,
            "quality_metrics_pass": screening.quality_metrics_pass,
            "matched_rule": screening.matched_rule,
            "emphasis": screening.emphasis,
        },
        "cross_match_message": cross_match_message,
        "cross_match_is_positive": cross_match_is_positive,
    }

    try:
        rendered_html = template.render(context)
        logger.debug("Report template rendered successfully.")
    except Exception as e:
        logger.error("Failed to render the report template: %s", e)
        raise

    # `--report-file` is documented as a name; this is what makes that true.
    report_file_path = contained_output_path(output_dir, report_file, "--report-file")
    try:
        with open(report_file_path, "w") as f:
            f.write(rendered_html)
        logger.info("Summary report generated and saved to %s", report_file_path)
    except Exception as e:
        logger.error("Failed to write the summary report: %s", e)
        raise
