name: vntyper
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.9.19
  - bioconda::bwa=0.7.18
  - samtools=1.20
  - bioconda::fastp=0.23.4
  - pandas=2.2.2
  - numpy=2.0.2
  - regex=2024.7.24
  - biopython=1.84
  - setuptools=72.2.0
  - jinja2=3.1.4
  - ca-certificates=2024.7.4
  - openssl=3.3.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - certifi=2024.8.30
  - igv-reports=1.13.0
  - plotly=5.24.0
  - openjdk=11.0.23
  - bcftools=1.21
