"""Run-local caller bundle applicability and no standalone generated bypass."""

from dataclasses import replace
from importlib import import_module

import pytest

from tests.unit.test_calibration_caller_bundle import bundle
from vntyper.scripts.calibration_caller_bundle import load_caller_model_bundle
from vntyper.scripts.canonical_json import canonical_json_bytes
from vntyper.scripts.run_configuration import resolve_run_configuration

pytestmark = pytest.mark.unit


def module():
    return import_module("vntyper.scripts.pipeline_caller_configuration")


def context_for(approved):
    applicability = approved.candidate.applicability
    return {
        "schema_version": "caller-runtime-context-v1",
        "evidence_domain": applicability.domain,
        "assembly": applicability.assemblies[0],
        "assay_class": applicability.assay_classes[0],
        "input_scope": applicability.input_scopes[0],
        "preprocessing_id": applicability.preprocessing_ids[0],
        "advntr_capture_policy": None,
    }


def configuration(root):
    path = bundle(root)
    approved = load_caller_model_bundle(path)
    context = root / "context.json"
    context.write_bytes(canonical_json_bytes(context_for(approved)))
    return path, context


def test_bundle_resolution_freezes_selected_values_and_preserves_legacy(tmp_path):
    path, context = configuration(tmp_path)
    legacy = resolve_run_configuration()
    result = resolve_run_configuration(calibration_bundle=path, calibration_context=context)
    assert result.caller_calibration.bundle.profile == result.decision_profile
    assert result.caller_calibration.context.assembly == "GRCh38"
    assert result.decision_profile.profile_kind == "generated"
    assert result.advntr == legacy.advntr
    assert resolve_run_configuration() == legacy
    with pytest.raises(TypeError):
        result.kestrel["injected"] = True
    with pytest.raises(ValueError):
        resolve_run_configuration(path / "decision-profile.json")


@pytest.mark.parametrize("combination", ["only-bundle", "only-context", "also-profile"])
def test_bundle_options_are_paired_and_exclusive(tmp_path, combination):
    path, context = configuration(tmp_path)
    kwargs = {"calibration_bundle": path, "calibration_context": context}
    if combination == "only-bundle":
        kwargs["calibration_context"] = None
    elif combination == "only-context":
        kwargs["calibration_bundle"] = None
    with pytest.raises(ValueError, match="paired|together|exclusive"):
        resolve_run_configuration("profile.json" if combination == "also-profile" else None, **kwargs)


@pytest.mark.parametrize(
    "field",
    [
        "extra",
        "schema_version",
        "evidence_domain",
        "assembly",
        "assay_class",
        "input_scope",
        "preprocessing_id",
        "advntr_capture_policy",
    ],
)
def test_closed_context_and_applicability_refuse_changes(tmp_path, field):
    path, context = configuration(tmp_path)
    approved = load_caller_model_bundle(path)
    document = context_for(approved)
    document[field] = "wrong"
    context.write_bytes(canonical_json_bytes(document))
    with pytest.raises(ValueError):
        resolve_run_configuration(calibration_bundle=path, calibration_context=context)


def test_context_codec_refuses_forged_digest_and_nonscalar(tmp_path):
    path, _ = configuration(tmp_path)
    document = context_for(load_caller_model_bundle(path))
    decoded = module().decode_caller_runtime_context(document)
    assert module().caller_runtime_context_document(decoded) == document
    with pytest.raises(ValueError, match="canonical"):
        module().caller_runtime_context_document(replace(decoded, sha256="0" * 64))
    with pytest.raises(ValueError):
        module().decode_caller_runtime_context([])
    document["assembly"] = []
    with pytest.raises(ValueError):
        module().decode_caller_runtime_context(document)


def test_preflight_requires_actual_assembly_and_explicit_advintr_for_dual(tmp_path):
    path, context = configuration(tmp_path)
    config = resolve_run_configuration(calibration_bundle=path, calibration_context=context)
    module().validate_caller_run_options(
        config.caller_calibration, assembly="GRCh38", extra_modules=(), threads=2, additional_commands=""
    )
    with pytest.raises(ValueError, match="assembly"):
        module().validate_caller_run_options(
            config.caller_calibration, assembly="hg38", extra_modules=(), threads=2, additional_commands=""
        )


def dual_configuration(
    root, mode="exact", producer=True, assembly=None, selected=None, model_bytes=b"invented model bytes"
):
    import hashlib

    from tests.unit.test_advntr_calibration_policy import capture_policy
    from tests.unit.test_calibration_export import _dual_setup, _rebind_payload
    from vntyper.modules.advntr.advntr_calibration_policy import (
        capture_policy_document,
        capture_policy_for_caller,
        decode_capture_policy,
    )
    from vntyper.scripts.calibration_export import export_calibration_bundle
    from vntyper.scripts.canonical_json import load_strict_json_object

    if selected is None:
        args = _dual_setup(root, mode)
    else:
        from unittest.mock import patch

        with patch("tests.unit.test_calibration_advntr_runtime_policy._caller", return_value=selected):
            args = _dual_setup(root, mode)
    payload = args.profile / "payload"
    # Decode the same selected values through the exporter before rebinding this
    # entirely invented fixture's native asset commitments.
    export_calibration_bundle(args, args.output)
    approved = load_caller_model_bundle(args.output)
    for path in args.output.iterdir():
        path.unlink()
    capture = capture_policy_for_caller(decode_capture_policy(capture_policy()), approved.caller_policy)
    sidecar = load_strict_json_object((payload / "advntr-policy.json").read_bytes())
    sidecar["capture_policy_sha256"] = capture.sha256
    sidecar["model_sha256"] = hashlib.sha256(model_bytes).hexdigest()
    (payload / "advntr-policy.json").write_bytes(canonical_json_bytes(sidecar))
    descriptor = load_strict_json_object((payload / "caller-bundle.json").read_bytes())
    descriptor["components"]["advntr-policy.json"] = hashlib.sha256(
        (payload / "advntr-policy.json").read_bytes()
    ).hexdigest()
    (payload / "caller-bundle.json").write_bytes(canonical_json_bytes(descriptor))
    if producer or assembly is not None:
        candidate_path = args.profile / "candidate.json"
        candidate = load_strict_json_object(candidate_path.read_bytes())
        if producer:
            candidate["producer"]["tool_versions"].update(advntr="2.4.0", advntr_build_id="a" * 64)
        if assembly is not None:
            candidate["applicability"]["assemblies"] = [assembly]
        candidate_path.write_bytes(canonical_json_bytes(candidate))
    _rebind_payload(args)
    export_calibration_bundle(args, args.output)
    approved = load_caller_model_bundle(args.output)
    document = context_for(approved)
    document["advntr_capture_policy"] = capture_policy_document(capture)
    context = root / "context.json"
    context.write_bytes(canonical_json_bytes(document))
    return args.output, context


@pytest.mark.parametrize("mode", ["legacy", "exact"])
def test_dual_policy_context_binds_full_capture_and_fixed_execution_options(tmp_path, mode):
    path, context = dual_configuration(tmp_path, mode)
    config = resolve_run_configuration(calibration_bundle=path, calibration_context=context)
    calibration = config.caller_calibration
    assert calibration.context.advntr_capture_policy.sha256 == calibration.bundle.advntr_policy.capture_policy_sha256
    assert config.advntr["calibrated_calling"]["mode"] == mode
    kwargs = {"assembly": "GRCh38", "extra_modules": ("advntr",), "threads": 2, "additional_commands": ""}
    module().validate_caller_run_options(calibration, **kwargs)
    for change in (
        {"extra_modules": ()},
        {"threads": 3},
        {"threads": True},
        {"additional_commands": "--prune-reverse"},
    ):
        with pytest.raises(ValueError):
            module().validate_caller_run_options(calibration, **(kwargs | change))


@pytest.mark.parametrize("change", ["capture-hash", "missing-capture", "missing-build"])
def test_dual_configuration_refuses_unbound_runtime_capture_and_producer(tmp_path, change):
    from vntyper.scripts.canonical_json import load_strict_json_object

    path, context = dual_configuration(tmp_path, producer=change != "missing-build")
    document = load_strict_json_object(context.read_bytes())
    if change == "capture-hash":
        document["advntr_capture_policy"]["parameters"]["threads"] = 3
    elif change == "missing-capture":
        document["advntr_capture_policy"] = None
    context.write_bytes(canonical_json_bytes(document))
    with pytest.raises(ValueError, match="capture|producer"):
        resolve_run_configuration(calibration_bundle=path, calibration_context=context)


def test_context_projection_requires_decoded_type():
    with pytest.raises(ValueError, match="decoded"):
        module().caller_runtime_context_document({})
